language: c
sudo: false
notifications: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
script:
  - build_platform esp8266
